### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tfx2001** [tfx2001/tinyusb#7]
MCU 平台的移植

- [x] Nordic @chenyingchun0312
- [ ] 新塘

设备类的支持

- [ ] HID
- [ ] Audio
- [ ] DFU
- [ ] MSC（待完善）

各个设备类的用例
- [x] CDC
- [ ] MSC

USB Host

- [ ] Host 协议栈

**Comment by chenyingchun0312** [comment]
nodic平台移植，我来试一下

**Comment by tfx2001** [comment]
move to https://github.com/RT-Thread-packages/tinyusb/issues/2
